### ISSUE TITLE
Could you explain how I can generate one myself?

### ISSUE THREAD

**Issue by xplshn** [11orZee/Floorp-AppImage#1]
Hi! Thanks for this awesome template. I wish to know how I could generate one of these, using https://github.com/xplshn/pelf
But instructions using whatever tooling you prefer are appreciated too!

**Comment by 11orZee** [comment]
> Привет! Спасибо за этот потрясающий шаблон. Я хотел бы знать, как я мог бы создать один из них, используя [https://github.com/xplshn/pelf ](https://github.com/xplshn/pelf) Но инструкции с использованием любого инструмента, который вы предпочитаете, тоже ценятся!

Hi! As far as I understand "PELF" has detailed instructions and relies on appimage. 
This is the simplest explanation for understanding how and what is assembled that I have only been able to find https://www.youtube.com/watch?v=Wy63jwjpNg4.

**Comment by xplshn** [comment]
Thanks!
